### ISSUE TITLE
[Unified Inventory/Inventory Plus] Assignment to undeclared global 'opened' (and 'itemstacks')

### ISSUE THREAD

**Issue by TriBlade9** [rubenwardy/smartfs#6]
Attempting to open a smartfs formspec with Unified Inventory results in this error:
`attempt to index global 'opened' (a nil value)`

Offending lines (76, 77):
```
opened = smartfs._show_(form,name,nil,true)
return {formspec=opened:_getFS_(false)}
```
Any info?
This also causes Unified Inventory to pretty much breakdown entirely.

**Comment by rubenwardy** [comment]
I wish I commented smartfs more. I can't remember anything :(

I will look to fix this soon.

**Comment by rubenwardy** [comment]
I think it's fixed. Can you try it?

**Comment by rubenwardy** [comment]
I don't see what else could be wrong. There are no code paths which return nil from _show_, afaik. I guess it is possible that the `local state` goes out of bounds when returned - does that happen in Lua?

https://github.com/rubenwardy/smartfs/blob/master/smartfs.lua#L241-L253

**Comment by TriBlade9** [comment]
I'll test.

**Comment by rubenwardy** [comment]
It works with the inventory in example.lua for me with Unified Inventory.

**Comment by TriBlade9** [comment]
Yep, working now. Thanks!
Awesome mod/library btw.

**Comment by rubenwardy** [comment]
What framework are you using? You probably need to supply a back button.

**Comment by TriBlade9** [comment]
Uhh, Unified Inventory?
How should a back button be implemented?

**Comment by rubenwardy** [comment]
Fixed. You don't need a back button.

**Comment by TriBlade9** [comment]
Yep, works now, thanks!
On an unrelated note, any idea why my craftitems aren't showing up in the UI creative list?

**Comment by TriBlade9** [comment]
Yep, works now, thanks!
On an unrelated note, any idea why my craftitems aren't showing up in the UI creative list?

**Comment by rubenwardy** [comment]
Have you checked that you don't have a not_in_creative_inventory group? I
can't think of anything else.

**Comment by TriBlade9** [comment]
Yeah, none of them have not_in_creative_inventory group. There's about 90 variants of each item though. x]

Thanks a lot for your help! I now have a working clothing/wearables mod.
